server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: test
      database: test
      port: 27017
      host: localhost
      auto-index-creation: true

      mongodb:
        authentication-database: test2
        database: test2
        port: 27017
        host: localhost
        auto-index-creation: true
